# Build settings
markdown: kramdown
permalink: pretty


# Dependencies
markdown:         kramdown
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            "The Translation Toolkit"
tagline:          
description:      "a working group of GO::DH"
host:    127.0.0.1
url: ""              
baseurl: "/translation-toolkit"
email:


paginate:         5
layout: blog-post

# Custom vars
version:          2.0.0


